apiVersion: batch/v1
kind: CronJob
metadata:
  name: basic-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
       template:
         spec:
           containers:
             - name: ubuntu
               image: ubuntu
               args:
                 - /bin/sh
                 - -c
                 - date; echo "HeLLo world"
           restartPolicy: OnFailure