apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      hostPort: 8090
      protocol: TCP
      name: nginx-port
    resources:
      requests:
        cpu: "0.2"
        memory: "200Mi"
      limits:
        cpu: "0.5"
        memory: "500Mi"
    volumeMounts:
     - name: nginx-vol
       mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
       claimName: nginx-pv
      
