apiVersion: v1
kind: PersistentVolume
metadata:
    name: host-path-pv
    labels:
        app: host-path
        env: prod
spec:
    storageClassName: nginx-pv
    capacity:
        storage: "5Gi"
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/var/tmp"
        type: DirectoryOrCreate

  
