apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: nginx
    env: prod
spec:
  containers:
   - name: nginx
     image: nginx:latest
     ports:
      - name: nginx
        containerPort: 80
        protocol: TCP
     env:
      - name: DBName
        value: ruxs
     resources:
       limits:
         cpu: "0.5"
         memory: "500Mi"
       requests:
         cpu: "0.2"
         memory: "200Mi"
     volumeMounts:
       - name: nginx-mount
         mountPath: /var/www/html
  volumes:
    - name: nginx-mount
      emptyDir:
        medium: Memory
        sizeLimit: 300Mi