apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-cicd
  labels:
    app: jenkins
    env: prod
spec:
  replicas: 1
  selector: 
    matchLabels: 
       app: jenkins
       env: prod
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
        env: prod
    spec:
      containers:
      - name: jenkins-conatiner
        image: jenkins-lts
        ports:
          - name: jenkins-port
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: jenkins-mount
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-mount
        nfs:
          server: 123.45.67
          path: /var/nfx/jenkins

---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-service
spec:
  type: NodePort
  ports:
    - name: jenkins-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: jenkins
    env: prod
    
         
