apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
       containers: 
        - name: alpine
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "echo Hello from k8s Jobs"]
       restartPolicy: Never #OnFailure
  backoffLimit: 4
  suspend: true
  ttlSecondsAfterFinished: 30
